### ISSUE TITLE
Doesn't work on newest version

### ISSUE THREAD

**Issue by abbeyroad7** [dretax/TabletopHax#1]
Game crashes

**Comment by dretax** [comment]
Thanks for the notice I will take a look.

**Comment by dretax** [comment]
Haven't gotten time yet, but will take a look this weekend.

**Comment by dretax** [comment]
@abbeyroad7 You messed up.
I updated the code a bit, but It works perfectly. Compile the project yourself..
![image](https://user-images.githubusercontent.com/1114109/87849887-72ad0480-c8ec-11ea-9b53-dcb9cc0dc3fe.png)
