### ISSUE TITLE
Instructions not clear, pc is on fire.

### ISSUE THREAD

**Issue by magnoelcabiadito** [dretax/TabletopHax#2]
Just kidding, but as someone thats very poor but had to but the 4 persons pack i was wondering if this still works or im too dumb to follow the instructions. i will probably have to learn to pack it myself like the past closed issue D:

**Comment by dretax** [comment]
I'll update it

**Comment by magnoelcabiadito** [comment]
:D my hero! I know its a bit bad that i ask this, as the game will eventually be updated and i will have to do this on my own. I will give it a try tomorrow.

**Comment by magnoelcabiadito** [comment]
Gave it a shot with a friend who understand a lot more of this than me. We tried for a good while but always ended up with compilation problems! D:

Here is a pic but its in spanish so i will translate if it helps. 
the name "singleton" does not exist on the current context
the type "monobegaviour" is defined in an assembly that is not referenced. add a reference to the assembly"
https://imgur.com/H40BsDL

**Comment by dretax** [comment]
I will make a quick tutorial video in some hours. Please wait until that happens.

**Comment by magnoelcabiadito** [comment]
Yasss!! lets go. Sure will dude!

**Comment by dretax** [comment]
Done. Readme.md
