### ISSUE TITLE
Tabletop Simulator Got Updated, Game Crashes When Using Hax

### ISSUE THREAD

**Issue by DisarmedSpy** [dretax/TabletopHax#3]
When using the DLL files, game now crashes.

**Comment by dretax** [comment]
Thats bad patching. Refer to video.

**Comment by DisarmedSpy** [comment]
I will say I was using the precompiled version and not compiling it myself, so it appears something has changed in the DLL files in order to require a user to compile now, rather than using the precompiled file. May I do a pull request with the newer precompiled files for those who do not have the knowledge, know-how, or space for Visual Studio?

**Comment by dretax** [comment]
@DisarmedSpy Sorry for the delay. Sure. Did you get it to work by self compiling and patching?

**Comment by DisarmedSpy** [comment]
@dretax It's no problem. After patching it still doesn't work. The game loads, however when attempting to load a DLC nothing happens. The store doesn't pop up, the game browser simply closes, shows the table, and that's it.

**Comment by DisarmedSpy** [comment]
So it's as if instead of loading the DLC, you just  hit close instead.

**Comment by dretax** [comment]
Alright. I will take a look at It today if i can

**Comment by DisarmedSpy** [comment]
Sounds good. Good luck

**Comment by dretax** [comment]
#4 working on it rn. Game was updated after a year lol...

**Comment by DisarmedSpy** [comment]
So I figured lol!

[Olivia Long - Chat @ Spike](https://spikenow.com/r/a/?ref=spike-organic-signature&_ts=x89k1)	[x89k1]

On February 28, 2021 at 16:15 GMT, DreTaX <notifications@github.com> wrote:

[#4](https://github.com/dretax/TabletopHax/issues/4) working on it rn. Game was updated after a year lol...

**Comment by dretax** [comment]
![image](https://user-images.githubusercontent.com/1114109/109426735-6eeb6f80-79ef-11eb-9d2d-7b921c476ea3.png)

Easy. Pushing updates. Test and closing issue.

**Comment by DisarmedSpy** [comment]
Sounds good! Glad it could be resolved and glad I could assist in some way. :)

**Comment by DisarmedSpy** [comment]
Issue is fixed with latest v1.3 update. Closing issue. Thank you much. :)
