### ISSUE TITLE
Issue after patching

### ISSUE THREAD

**Issue by ARandomGuy15** [dretax/TabletopHax#4]
I've applied the patch as guided to in the provided video.
Game launches, however attempts to open a dlc simply closes the menu leaving the empty table that sits behind the game select menu.

**Comment by dretax** [comment]
What OS? I will check it out.

**Comment by ARandomGuy15** [comment]
Windows 10 Home edition
I'll attempt patching with the video guide one more time to see if I get the same results

*edit> I arrived at the same outcome this time around. idk if it'll help, but I attached the dll's so you can confirm if I messed up the patching on my side.
[PatchedDLLs.zip](https://github.com/dretax/TabletopHax/files/6008998/PatchedDLLs.zip)

When building the files I included the 2 dll's you mentioned in the video, and they successfully built, but It failed to obtain a reference to 'Assembly-CSharp-firstpass' and 'UnityEngine'. Adding the additional dll's to fix those error messages made no changes to the situation

**Comment by dretax** [comment]
@ARandomGuy15 sorry for the delay. Where did you see it failed to obtain reference?

**Comment by ARandomGuy15** [comment]
![image](https://user-images.githubusercontent.com/79144853/109387083-0ea4f100-794f-11eb-9bc0-e1b6f1125bd2.png)
simply in the output of VS
Rebuild started...
1>------ Rebuild All started: Project: Tabletopatcher, Configuration: Release Any CPU ------
2>------ Rebuild All started: Project: DLCDreTaX, Configuration: Release Any CPU ------
2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(2123,5): warning MSB3245: Could not resolve this reference. Could not locate the assembly "Assembly-CSharp-firstpass, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.
2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(2123,5): warning MSB3245: Could not resolve this reference. Could not locate the assembly "UnityEngine, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.
2>  DLCDreTaX -> D:\Desktop\TabletopHax-master\DLCDreTaX\bin\Release\DLCDreTaX.dll
1>  Tabletopatcher -> D:\Desktop\TabletopHax-master\Tabletopatcher\bin\Release\Tabletopatcher.exe
========== Rebuild All: 2 succeeded, 0 failed, 0 skipped ==========

**Comment by dretax** [comment]
Thanks for the report, it is fixed.
