### ISSUE TITLE
Latest update broke hack

### ISSUE THREAD

**Issue by DisarmedSpy** [dretax/TabletopHax#5]
Welp, they released another update to Tabletop Simulator and again broke the hack so now the game crashes when being loaded in.

**Comment by dretax** [comment]
I will take a look soon.

**Comment by DisarmedSpy** [comment]
Sounds good. Figured I'd give you a heads up

**Comment by dretax** [comment]
Have you tried re patching the fresh binaries?

**Comment by DisarmedSpy** [comment]
Yes, I did.

**Comment by Polarvargen** [comment]
Same issue here. Fresh install, DLLs  replaced and crash on startup

**Comment by dretax** [comment]
Alright. I will take a look soon, thanks for the report.

**Comment by DisarmedSpy** [comment]
No problem!

**Comment by DisarmedSpy** [comment]
Any luck thus far?

**Comment by dretax** [comment]
Sorry, havent had the time for it. Maybe today.

**Comment by DisarmedSpy** [comment]
> Sorry, havent had the time for it. Maybe today.

Hey no problem take your time!

**Comment by dretax** [comment]
Sorry for the extreme delay, so many things i need to do at once. I'm looking at it now

**Comment by DisarmedSpy** [comment]
It's no problem! There's more important shit than this lol

[Olivia Long - Chat @ Spike](https://spikenow.com/r/a/?ref=spike-organic-signature&_ts=107z1o)	[107z1o]

On April 27, 2021 at 19:54 GMT, DreTaX ***@***.***> wrote:

Sorry for the extreme delay, so many things i need to do at once. I'm looking at it now

**Comment by dretax** [comment]
Sorry for the extreme delay. First thing im doing in the morning is this.

**Comment by DisarmedSpy** [comment]
Hey its no problem! Take your time still. :) I kinda stumbled upon something similar which unlocks DLC for other games as well

[Olivia Long - Chat @ Spike](https://spikenow.com/r/a/?ref=spike-organic-signature&_ts=10qprt)	[10qprt]

On May 7, 2021 at 22:54 GMT, DreTaX ***@***.***> wrote:

Sorry for the extreme delay. First thing im doing in the morning is this.

**Comment by dretax** [comment]
![image](https://user-images.githubusercontent.com/1114109/117516625-e8787e80-af99-11eb-936c-83762df4f8a4.png)
Did you use the patcher or the binaries?
The patcher still works, just copied over the latest assembly to patch. The uploaded binaries obviously will not work since the files changed. I think Im gonna include the patcher in the zip file as well.

**Comment by DisarmedSpy** [comment]
Makes sense but weird as I used the patcher and it didn't work. But oh well thankfully found an alternative so no harm, could have just been me messing up, lol

[Olivia Long - Chat @ Spike](https://spikenow.com/r/a/?ref=spike-organic-signature&_ts=10qr89)	[10qr89]

On May 7, 2021 at 23:09 GMT, DreTaX ***@***.***> wrote:

[image](https://user-images.githubusercontent.com/1114109/117516625-e8787e80-af99-11eb-936c-83762df4f8a4.png)
Did you use the patcher or the binaries?
The patcher still works, just copied over the latest assembly to patch. The uploaded binaries obviously will not work since the files changed. I think Im gonna include the patcher in the zip file as well.

**Comment by dretax** [comment]
Can you test if it works now?

**Comment by DisarmedSpy** [comment]
> Can you test if it works now?

Works now, so strange. No idea what I was doing wrong when compiling.
