### ISSUE TITLE
Kickstarter pointer

### ISSUE THREAD

**Issue by Lonick32** [dretax/TabletopHax#6]
I know it has something to do with SteamManager but I can't figure it out maybe you can and unlock the kickstarter pointer

**Comment by dretax** [comment]
What exactly are you trying to achieve?

**Comment by Lonick32** [comment]
> What exactly are you trying to achieve?

There's a "kickstarter pointer" and I think that it's unlockable might be a hidden DLC or something I don't know exactly
![Screenshot_5](https://user-images.githubusercontent.com/39029077/156935370-14fb3b0a-a558-4e17-89c9-7611f01217e5.png)

**Comment by dretax** [comment]
Apologies for the late reply @Lonick32 
Yes It is unlockable, I have done this myself in the past before.

Reversing this is easy as this:
![image](https://user-images.githubusercontent.com/1114109/159118440-253ec8e1-8f7c-49e7-8965-086d37f38b37.png)

There is a PointerLook enum that stores the current look of your mouse. Diving further to the "kickstarter" key there are several references that are using steammanager class's static field:
![image](https://user-images.githubusercontent.com/1114109/159118619-301c7e4c-59f9-42be-a34a-80d5612b6443.png)

![image](https://user-images.githubusercontent.com/1114109/159118645-bc5bf2b8-363c-410b-9c34-17fb0769e70e.png)

A simple hook after these instructions would do the trick. My question is the following though: Do you plan on implementing this on your own, or you are asking me to do it?

**Comment by Lonick32** [comment]
I mean if you could do it it would be amazing I have unlocked all the DLCs by myself I just made it return true but I don't know if this is the same

**Comment by dretax** [comment]
I'll add It soon then.

**Comment by Lonick32** [comment]
🙏

**Comment by dretax** [comment]
https://github.com/dretax/TabletopHax/commit/2b10eeeb7b0efae79d7927a295aacd53babb9b01
