### ISSUE TITLE
Latest update 13.2 breaks hack?

### ISSUE THREAD

**Issue by promethyes** [dretax/TabletopHax#7]
TTS updated to v13.2 as of yesterday 15/09/22.

DLLs seemed to be broken and when attempting to refix encountered following issue:

Error Loading DLC games: bool ExtensionMethods.TryAdd<!0>(System.Collections.Generic.List` 1<!!0>,!!0) <3>

Any help with this? Thanks in advance

**Comment by dretax** [comment]
Thanks for the notice, will check

**Comment by dretax** [comment]
@promethyes should be fixed, let me know.
