### ISSUE TITLE
Having a error saying "Could Not Verify DLCDretax Version 1.00"

### ISSUE THREAD

**Issue by NinjaLeon** [dretax/TabletopHax#9]
It was that or something similar, this was a couple of hours ago so I can remember but couldn't basically it couldn't find dlc files because of DLCDretax Version 1:00.

**Comment by dretax** [comment]
What is this about?

**Comment by NinjaLeon** [comment]
Sorry, I know it has been a month but I got logged out of this account. I put all the folders in the correct place but when I go onto table top sim, none of the dlcs load and then it pops up "dlcdtrax can't be found"

**Comment by NinjaLeon** [comment]
It's still popping up

**Comment by dretax** [comment]
> Sorry, I know it has been a month but I got logged out of this account. I put all the folders in the correct place but when I go onto table top sim, none of the dlcs load and then it pops up "dlcdtrax can't be found"

Hey

Did you install the zip file correctly?
You need to overwrite the dlls in the Managed folder.

**Comment by NinjaLeon** [comment]
Maybe That was the problem. Thanks. Also keep it up! I love that I can play all the DLC. You a real one.
